// Mock data for CamMarket

// User data
export const mockUser = {
  id: 1,
  name: 'Jean Kamga',
  email: 'jean.kamga@example.com',
  phone: '+237 677 123 456',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
  region: 'littoral',
  joinDate: '2024-01-15',
  verified: true,
};

// Mock orders
export const mockOrders = [
  {
    id: 'ORD-2024-001',
    date: '2024-11-15',
    status: 'delivered' as 'delivered' | 'processing' | 'cancelled',
    total: 45000,
    items: [
      { productId: 1, quantity: 2, price: 15000 },
      { productId: 2, quantity: 1, price: 15000 },
    ],
    shippingAddress: {
      name: 'Jean Kamga',
      phone: '+237 677 123 456',
      region: 'littoral',
      city: 'Douala',
      address: 'Akwa, Rue de la Joie, Immeuble 45',
    },
    trackingNumber: 'CAM2024001234',
  },
  {
    id: 'ORD-2024-002',
    date: '2024-11-12',
    status: 'processing' as 'delivered' | 'processing' | 'cancelled',
    total: 78000,
    items: [
      { productId: 3, quantity: 1, price: 78000 },
    ],
    shippingAddress: {
      name: 'Jean Kamga',
      phone: '+237 677 123 456',
      region: 'littoral',
      city: 'Douala',
      address: 'Akwa, Rue de la Joie, Immeuble 45',
    },
    trackingNumber: 'CAM2024001235',
  },
  {
    id: 'ORD-2024-003',
    date: '2024-11-08',
    status: 'cancelled' as 'delivered' | 'processing' | 'cancelled',
    total: 25000,
    items: [
      { productId: 5, quantity: 5, price: 5000 },
    ],
    shippingAddress: {
      name: 'Jean Kamga',
      phone: '+237 677 123 456',
      region: 'littoral',
      city: 'Douala',
      address: 'Akwa, Rue de la Joie, Immeuble 45',
    },
  },
];

// Mock addresses
export const mockAddresses = [
  {
    id: 1,
    name: 'Jean Kamga',
    phone: '+237 677 123 456',
    region: 'littoral',
    city: 'Douala',
    address: 'Akwa, Rue de la Joie, Immeuble 45',
    isDefault: true,
  },
  {
    id: 2,
    name: 'Jean Kamga',
    phone: '+237 677 123 456',
    region: 'centre',
    city: 'Yaoundé',
    address: 'Bastos, Avenue Kennedy, Résidence 12',
    isDefault: false,
  },
];

// Seller/Vendor Mock Data
export const mockVendor = {
  id: 1,
  storeName: 'Kamga Electronics',
  ownerName: 'Jean Kamga',
  phone: '+237 677 123 456',
  email: 'jean.kamga@example.com',
  region: 'littoral',
  city: 'Douala',
  storeLogo: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=400',
  storeBanner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200',
  storeDescription: 'Your trusted source for quality electronics in Douala',
  storeDescriptionFr: 'Votre source de confiance pour l\'électronique de qualité à Douala',
  activeRegions: ['littoral', 'centre', 'west'],
  joinDate: '2023-06-15',
  verified: true,
  rating: 4.8,
  totalSales: 1256,
  totalProducts: 48,
};

export const mockSellerProducts = [
  {
    id: 1,
    name: 'Samsung Galaxy A54',
    nameFr: 'Samsung Galaxy A54',
    category: 'electronics',
    subcategory: 'smartphones',
    price: 285000,
    stock: 15,
    status: 'active',
    images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800'],
    description: 'Latest Samsung smartphone with 128GB storage',
    descriptionFr: 'Dernier smartphone Samsung avec stockage de 128 Go',
    regions: ['littoral', 'centre'],
    deliveryOptions: ['standard', 'express'],
    views: 456,
    sales: 23,
    createdAt: '2024-10-15',
  },
  {
    id: 2,
    name: 'HP Laptop 15-inch',
    nameFr: 'Ordinateur portable HP 15 pouces',
    category: 'electronics',
    subcategory: 'computers',
    price: 450000,
    stock: 8,
    status: 'active',
    images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800'],
    description: 'Intel Core i5, 8GB RAM, 512GB SSD',
    descriptionFr: 'Intel Core i5, 8 Go RAM, 512 Go SSD',
    regions: ['littoral', 'centre', 'west'],
    deliveryOptions: ['standard'],
    views: 789,
    sales: 12,
    createdAt: '2024-09-20',
  },
  {
    id: 3,
    name: 'Wireless Headphones',
    nameFr: 'Écouteurs sans fil',
    category: 'electronics',
    subcategory: 'audio',
    price: 35000,
    stock: 0,
    status: 'out-of-stock',
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'],
    description: 'Bluetooth 5.0, noise cancellation',
    descriptionFr: 'Bluetooth 5.0, réduction de bruit',
    regions: ['littoral'],
    deliveryOptions: ['standard', 'express', 'pickup'],
    views: 234,
    sales: 45,
    createdAt: '2024-08-10',
  },
];

export const mockSellerOrders = [
  {
    id: 'ORD-2024-101',
    customerName: 'Marie Nkwenti',
    customerPhone: '+237 690 234 567',
    date: '2024-11-16',
    status: 'pending' as 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled',
    total: 285000,
    items: [
      { productId: 1, productName: 'Samsung Galaxy A54', quantity: 1, price: 285000 },
    ],
    shippingAddress: {
      name: 'Marie Nkwenti',
      phone: '+237 690 234 567',
      region: 'centre',
      city: 'Yaoundé',
      address: 'Essos, Quartier Fouda',
    },
    paymentMethod: 'MTN Mobile Money',
    trackingNumber: null,
  },
  {
    id: 'ORD-2024-102',
    customerName: 'Paul Tchoumi',
    customerPhone: '+237 677 345 678',
    date: '2024-11-15',
    status: 'processing' as 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled',
    total: 450000,
    items: [
      { productId: 2, productName: 'HP Laptop 15-inch', quantity: 1, price: 450000 },
    ],
    shippingAddress: {
      name: 'Paul Tchoumi',
      phone: '+237 677 345 678',
      region: 'littoral',
      city: 'Douala',
      address: 'Bonamoussadi, Carrefour Ange Raphaël',
    },
    paymentMethod: 'Orange Money',
    trackingNumber: 'CAM2024VND001',
  },
  {
    id: 'ORD-2024-103',
    customerName: 'Aisha Bello',
    customerPhone: '+237 699 456 789',
    date: '2024-11-14',
    status: 'shipped' as 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled',
    total: 70000,
    items: [
      { productId: 3, productName: 'Wireless Headphones', quantity: 2, price: 35000 },
    ],
    shippingAddress: {
      name: 'Aisha Bello',
      phone: '+237 699 456 789',
      region: 'west',
      city: 'Bafoussam',
      address: 'Tamdja, Rond-point Marché',
    },
    paymentMethod: 'MTN Mobile Money',
    trackingNumber: 'CAM2024VND002',
  },
  {
    id: 'ORD-2024-104',
    customerName: 'Divine Fopa',
    customerPhone: '+237 680 567 890',
    date: '2024-11-12',
    status: 'delivered' as 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled',
    total: 285000,
    items: [
      { productId: 1, productName: 'Samsung Galaxy A54', quantity: 1, price: 285000 },
    ],
    shippingAddress: {
      name: 'Divine Fopa',
      phone: '+237 680 567 890',
      region: 'littoral',
      city: 'Douala',
      address: 'Akwa, Boulevard de la Liberté',
    },
    paymentMethod: 'Cash on Delivery',
    trackingNumber: 'CAM2024VND003',
  },
];

export const mockSellerAnalytics = {
  salesByRegion: [
    { region: 'littoral', regionName: 'Littoral', sales: 2450000, orders: 45 },
    { region: 'centre', regionName: 'Centre', sales: 1890000, orders: 32 },
    { region: 'west', regionName: 'West', sales: 1250000, orders: 28 },
    { region: 'north-west', regionName: 'North-West', sales: 890000, orders: 15 },
    { region: 'south-west', regionName: 'South-West', sales: 670000, orders: 12 },
  ],
  productPerformance: [
    { product: 'Samsung Galaxy A54', sales: 6555000, units: 23, views: 456 },
    { product: 'HP Laptop 15-inch', sales: 5400000, units: 12, views: 789 },
    { product: 'Wireless Headphones', sales: 1575000, units: 45, views: 234 },
  ],
  conversionRate: 5.8,
  topViewedProducts: [
    { id: 2, name: 'HP Laptop 15-inch', views: 789 },
    { id: 1, name: 'Samsung Galaxy A54', views: 456 },
    { id: 3, name: 'Wireless Headphones', views: 234 },
  ],
};

export const mockSellerPayments = {
  walletBalance: 8650000,
  pendingBalance: 735000,
  totalEarnings: 12890000,
  transactions: [
    {
      id: 'TXN-2024-201',
      date: '2024-11-10',
      amount: 450000,
      status: 'completed' as 'pending' | 'completed' | 'failed',
      method: 'MTN Mobile Money',
      type: 'withdrawal' as 'sale' | 'withdrawal',
      reference: '+237 677 123 456',
    },
    {
      id: 'TXN-2024-202',
      date: '2024-11-15',
      amount: 285000,
      status: 'pending' as 'pending' | 'completed' | 'failed',
      method: 'Orange Money',
      type: 'withdrawal' as 'sale' | 'withdrawal',
      reference: '+237 677 123 456',
    },
    {
      id: 'TXN-2024-203',
      date: '2024-11-16',
      amount: 285000,
      status: 'completed' as 'pending' | 'completed' | 'failed',
      method: 'Sale',
      type: 'sale' as 'sale' | 'withdrawal',
      reference: 'ORD-2024-101',
    },
  ],
};

export const regions = [
  { 
    id: 'far-north', 
    name: 'Far North', 
    nameFr: 'Extrême-Nord', 
    color: '#FF6B6B',
    image: 'https://images.unsplash.com/photo-1589785131022-61f0d5f78307?w=1200',
    description: 'Experience the unique Sahelian culture and traditional crafts',
    descriptionFr: 'Découvrez la culture sahélienne unique et l\'artisanat traditionnel',
    vendorCount: 45,
    productCount: 132
  },
  { 
    id: 'north', 
    name: 'North', 
    nameFr: 'Nord', 
    color: '#4ECDC4',
    image: 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=1200',
    description: 'Explore agricultural treasures and local markets',
    descriptionFr: 'Explorez les trésors agricoles et les marchés locaux',
    vendorCount: 38,
    productCount: 156
  },
  { 
    id: 'adamawa', 
    name: 'Adamawa', 
    nameFr: 'Adamaoua', 
    color: '#45B7D1',
    image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=1200',
    description: 'Discover highland products and pastoral specialties',
    descriptionFr: 'Découvrez les produits des hautes terres et spécialités pastorales',
    vendorCount: 29,
    productCount: 98
  },
  { 
    id: 'east', 
    name: 'East', 
    nameFr: 'Est', 
    color: '#96CEB4',
    image: 'https://images.unsplash.com/photo-1542744095-291d1f67b221?w=1200',
    description: 'Forest products and traditional artifacts await',
    descriptionFr: 'Produits forestiers et artefacts traditionnels vous attendent',
    vendorCount: 34,
    productCount: 112
  },
  { 
    id: 'centre', 
    name: 'Centre', 
    nameFr: 'Centre', 
    color: '#FFEAA7',
    image: 'https://images.unsplash.com/photo-1531368606854-98a73fb2c0d1?w=1200',
    description: 'The heart of Cameroon with diverse urban markets',
    descriptionFr: 'Le cœur du Cameroun avec des marchés urbains diversifiés',
    vendorCount: 156,
    productCount: 542
  },
  { 
    id: 'littoral', 
    name: 'Littoral', 
    nameFr: 'Littoral', 
    color: '#74B9FF',
    image: 'https://images.unsplash.com/photo-1553531087-b4b52ab446c0?w=1200',
    description: 'Coastal delights and Douala\'s vibrant marketplace',
    descriptionFr: 'Délices côtiers et marché animé de Douala',
    vendorCount: 203,
    productCount: 687
  },
  { 
    id: 'west', 
    name: 'West', 
    nameFr: 'Ouest', 
    color: '#A29BFE',
    image: 'https://images.unsplash.com/photo-1609137144813-7d9921338f24?w=1200',
    description: 'Rich cultural heritage and artisanal crafts',
    descriptionFr: 'Riche patrimoine culturel et artisanat',
    vendorCount: 87,
    productCount: 234
  },
  { 
    id: 'northwest', 
    name: 'Northwest', 
    nameFr: 'Nord-Ouest', 
    color: '#FD79A8',
    image: 'https://images.unsplash.com/photo-1551775899-0ab0447f3a88?w=1200',
    description: 'Mountain products and traditional textiles',
    descriptionFr: 'Produits de montagne et textiles traditionnels',
    vendorCount: 72,
    productCount: 198
  },
  { 
    id: 'southwest', 
    name: 'Southwest', 
    nameFr: 'Sud-Ouest', 
    color: '#FDCB6E',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=1200',
    description: 'Volcanic soil treasures and coastal specialties',
    descriptionFr: 'Trésors du sol volcanique et spécialités côtières',
    vendorCount: 68,
    productCount: 176
  },
  { 
    id: 'south', 
    name: 'South', 
    nameFr: 'Sud', 
    color: '#6C5CE7',
    image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200',
    description: 'Forest resources and coastal delicacies',
    descriptionFr: 'Ressources forestières et délices côtiers',
    vendorCount: 51,
    productCount: 143
  }
];

export const categories = [
  { 
    id: 'foodstuff', 
    name: 'Foodstuff', 
    nameFr: 'Produits Alimentaires', 
    icon: 'UtensilsCrossed',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZnJpY2FuJTIwZm9vZCUyMGluZ3JlZGllbnRzfGVufDF8fHx8MTc2MzMyNjc3N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Fresh local ingredients and traditional foods',
    descriptionFr: 'Ingrédients locaux frais et aliments traditionnels'
  },
  { 
    id: 'electronics', 
    name: 'Electronics', 
    nameFr: 'Électronique', 
    icon: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGVjdHJvbmljcyUyMHNtYXJ0cGhvbmV8ZW58MXx8fHwxNzYzMjgxNTIxfDA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Latest gadgets and electronic devices',
    descriptionFr: 'Derniers gadgets et appareils électroniques'
  },
  { 
    id: 'fashion', 
    name: 'Fashion', 
    nameFr: 'Mode', 
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1667366925513-573975457271?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZnJpY2FuJTIwZmFzaGlvbiUyMGNsb3RoaW5nfGVufDF8fHx8MTc2MzMxNDU0OXww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Traditional and modern clothing styles',
    descriptionFr: 'Styles vestimentaires traditionnels et modernes'
  },
  { 
    id: 'agriculture', 
    name: 'Agriculture', 
    nameFr: 'Agriculture', 
    icon: 'Wheat',
    image: 'https://images.unsplash.com/photo-1509110646989-7ca4308edb3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZnJpY2FuJTIwYWdyaWN1bHR1cmUlMjBmYXJtaW5nfGVufDF8fHx8MTc2MzM3OTU0MXww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Fresh farm produce and agricultural products',
    descriptionFr: 'Produits agricoles et récoltes fraîches'
  },
  { 
    id: 'services', 
    name: 'Services', 
    nameFr: 'Services', 
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1746171114403-f4c4877b1f04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZnJpY2FuJTIwbWFya2V0cGxhY2UlMjBjb2xvcmZ1bHxlbnwxfHx8fDE3NjMzNzk1NDB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Professional services and local businesses',
    descriptionFr: 'Services professionnels et entreprises locales'
  },
  { 
    id: 'handcraft', 
    name: 'Handcraft', 
    nameFr: 'Artisanat', 
    icon: 'Palette',
    image: 'https://images.unsplash.com/photo-1682668701024-b6508708a764?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZnJpY2FuJTIwaGFuZGNyYWZ0JTIwYXJ0fGVufDF8fHx8MTc2MzM3OTU0Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    description: 'Handmade crafts and traditional artwork',
    descriptionFr: 'Artisanat fait main et œuvres d\'art traditionnelles'
  }
];

export interface Product {
  id: number;
  name: string;
  nameFr: string;
  price: number;
  region: string;
  category: string;
  image: string;
  seller: string;
  rating: number;
  stock: number;
  isFlashSale: boolean;
  discount?: number;
  condition: 'new' | 'used';
  deliveryOptions: string[];
  description?: string;
  descriptionFr?: string;
}

export const products: Product[] = [
  {
    id: 1,
    name: 'Fresh Ndole Leaves',
    nameFr: 'Feuilles de Ndolé Fraîches',
    price: 2500,
    region: 'centre',
    category: 'foodstuff',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Mama Agnes',
    rating: 4.8,
    stock: 50,
    isFlashSale: true,
    discount: 20,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Fresh organic Ndole leaves from Centre Region',
    descriptionFr: 'Feuilles de Ndolé bio fraîches de la région du Centre'
  },
  {
    id: 2,
    name: 'Samsung Galaxy A54',
    nameFr: 'Samsung Galaxy A54',
    price: 285000,
    region: 'littoral',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'TechHub Douala',
    rating: 4.9,
    stock: 15,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'Brand new Samsung Galaxy A54 with warranty',
    descriptionFr: 'Samsung Galaxy A54 neuf avec garantie'
  },
  {
    id: 3,
    name: 'Traditional Ankara Dress',
    nameFr: 'Robe Ankara Traditionnelle',
    price: 18500,
    region: 'west',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1667366925513-573975457271?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Fashion Boutique',
    rating: 4.7,
    stock: 8,
    isFlashSale: true,
    discount: 15,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup', 'inter-region'],
    description: 'Beautiful handmade Ankara dress',
    descriptionFr: 'Belle robe Ankara faite à la main'
  },
  {
    id: 4,
    name: 'Organic Cocoa Beans (5kg)',
    nameFr: 'Fèves de Cacao Bio (5kg)',
    price: 12000,
    region: 'southwest',
    category: 'agriculture',
    image: 'https://images.unsplash.com/photo-1509110646989-7ca4308edb3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Agro Southwest',
    rating: 5.0,
    stock: 100,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['inter-region', 'pickup'],
    description: 'Premium quality organic cocoa beans',
    descriptionFr: 'Fèves de cacao biologiques de qualité supérieure'
  },
  {
    id: 5,
    name: 'Handwoven Basket Set',
    nameFr: 'Ensemble de Paniers Tissés',
    price: 8500,
    region: 'northwest',
    category: 'handcraft',
    image: 'https://images.unsplash.com/photo-1682668701024-b6508708a764?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Bamenda Crafts',
    rating: 4.6,
    stock: 25,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Traditional handwoven baskets',
    descriptionFr: 'Paniers traditionnels tissés à la main'
  },
  {
    id: 6,
    name: 'Grilled Fish Service',
    nameFr: 'Service Poisson Braisé',
    price: 5000,
    region: 'littoral',
    category: 'services',
    image: 'https://images.unsplash.com/photo-1746171114403-f4c4877b1f04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Chez Marie',
    rating: 4.9,
    stock: 999,
    isFlashSale: true,
    discount: 10,
    condition: 'new',
    deliveryOptions: ['home-delivery'],
    description: 'Fresh grilled fish delivery service',
    descriptionFr: 'Service de livraison de poisson grillé frais'
  },
  {
    id: 7,
    name: 'Wireless Bluetooth Earbuds',
    nameFr: 'Écouteurs Bluetooth Sans Fil',
    price: 25000,
    region: 'north',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Garoua Electronics',
    rating: 4.7,
    stock: 30,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'High quality wireless earbuds',
    descriptionFr: 'Écouteurs sans fil de haute qualité'
  },
  {
    id: 8,
    name: 'Traditional Kaba Ngondo Outfit',
    nameFr: 'Tenue Kaba Ngondo Traditionnelle',
    price: 35000,
    region: 'littoral',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1667366925513-573975457271?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Fashion Boutique',
    rating: 4.8,
    stock: 12,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Authentic Kaba Ngondo traditional outfit',
    descriptionFr: 'Tenue traditionnelle Kaba Ngondo authentique'
  },
  {
    id: 9,
    name: 'Fresh Cassava (10kg)',
    nameFr: 'Manioc Frais (10kg)',
    price: 4500,
    region: 'east',
    category: 'agriculture',
    image: 'https://images.unsplash.com/photo-1509110646989-7ca4308edb3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Bertoua Farms',
    rating: 4.9,
    stock: 200,
    isFlashSale: true,
    discount: 25,
    condition: 'new',
    deliveryOptions: ['pickup', 'inter-region'],
    description: 'Fresh cassava from East Region farms',
    descriptionFr: 'Manioc frais des fermes de la région de l\'Est'
  },
  {
    id: 10,
    name: 'Wooden Sculpture Set',
    nameFr: 'Ensemble de Sculptures en Bois',
    price: 15000,
    region: 'south',
    category: 'handcraft',
    image: 'https://images.unsplash.com/photo-1682668701024-b6508708a764?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Kribi Artisans',
    rating: 5.0,
    stock: 18,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'Handcrafted wooden sculptures',
    descriptionFr: 'Sculptures en bois artisanales'
  },
  {
    id: 11,
    name: 'Smart Watch Pro',
    nameFr: 'Montre Connectée Pro',
    price: 45000,
    region: 'centre',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'TechHub Douala',
    rating: 4.8,
    stock: 25,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup', 'inter-region'],
    description: 'Advanced smartwatch with fitness tracking',
    descriptionFr: 'Montre connectée avancée avec suivi fitness'
  },
  {
    id: 12,
    name: 'Palm Oil (5 Liters)',
    nameFr: 'Huile de Palme (5 Litres)',
    price: 7500,
    region: 'southwest',
    category: 'foodstuff',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Agro Southwest',
    rating: 4.9,
    stock: 150,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Pure organic palm oil',
    descriptionFr: 'Huile de palme bio pure'
  },
  {
    id: 13,
    name: 'Laptop Computer HP',
    nameFr: 'Ordinateur Portable HP',
    price: 350000,
    region: 'littoral',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'TechHub Douala',
    rating: 4.8,
    stock: 10,
    isFlashSale: true,
    discount: 15,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'HP laptop with Intel processor',
    descriptionFr: 'Ordinateur portable HP avec processeur Intel'
  },
  {
    id: 14,
    name: 'Honey (1 Liter)',
    nameFr: 'Miel (1 Litre)',
    price: 6000,
    region: 'adamawa',
    category: 'foodstuff',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Adamawa Honey',
    rating: 5.0,
    stock: 45,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup', 'inter-region'],
    description: 'Pure natural honey from Adamawa highlands',
    descriptionFr: 'Miel naturel pur des hautes terres d\'Adamaoua'
  },
  {
    id: 15,
    name: 'Kente Cloth',
    nameFr: 'Tissu Kente',
    price: 22000,
    region: 'west',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1667366925513-573975457271?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'West Region Textiles',
    rating: 4.9,
    stock: 18,
    isFlashSale: true,
    discount: 20,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'Authentic Kente traditional fabric',
    descriptionFr: 'Tissu Kente traditionnel authentique'
  },
  {
    id: 16,
    name: 'Fresh Vegetables Bundle',
    nameFr: 'Paquet de Légumes Frais',
    price: 3500,
    region: 'far-north',
    category: 'agriculture',
    image: 'https://images.unsplash.com/photo-1509110646989-7ca4308edb3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Maroua Farms',
    rating: 4.5,
    stock: 80,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Assorted fresh vegetables',
    descriptionFr: 'Légumes frais assortis'
  },
  {
    id: 17,
    name: 'Pottery Set',
    nameFr: 'Ensemble de Poterie',
    price: 12000,
    region: 'adamawa',
    category: 'handcraft',
    image: 'https://images.unsplash.com/photo-1682668701024-b6508708a764?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Ngaoundéré Crafts',
    rating: 4.7,
    stock: 22,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['pickup', 'inter-region'],
    description: 'Traditional handmade pottery',
    descriptionFr: 'Poterie traditionnelle faite à la main'
  },
  {
    id: 18,
    name: 'iPhone 13',
    nameFr: 'iPhone 13',
    price: 450000,
    region: 'centre',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Mama Agnes Market',
    rating: 4.9,
    stock: 5,
    isFlashSale: false,
    condition: 'used',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'iPhone 13 in excellent condition',
    descriptionFr: 'iPhone 13 en excellent état'
  },
  {
    id: 19,
    name: 'Smoked Fish (2kg)',
    nameFr: 'Poisson Fumé (2kg)',
    price: 8000,
    region: 'south',
    category: 'foodstuff',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Kribi Fresh Seafood',
    rating: 4.8,
    stock: 35,
    isFlashSale: true,
    discount: 12,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'Traditional smoked fish',
    descriptionFr: 'Poisson fumé traditionnel'
  },
  {
    id: 20,
    name: 'Traditional Beads Necklace',
    nameFr: 'Collier de Perles Traditionnelles',
    price: 9500,
    region: 'northwest',
    category: 'handcraft',
    image: 'https://images.unsplash.com/photo-1682668701024-b6508708a764?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Bamenda Fashion House',
    rating: 4.6,
    stock: 40,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Handcrafted traditional beads necklace',
    descriptionFr: 'Collier de perles traditionnel fait à la main'
  },
  {
    id: 21,
    name: 'Rice (25kg)',
    nameFr: 'Riz (25kg)',
    price: 18000,
    region: 'north',
    category: 'foodstuff',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Garoua Market',
    rating: 4.7,
    stock: 120,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['pickup', 'inter-region'],
    description: 'Quality rice from North Region',
    descriptionFr: 'Riz de qualité de la région du Nord'
  },
  {
    id: 22,
    name: 'Wood Carvings',
    nameFr: 'Sculptures en Bois',
    price: 16500,
    region: 'east',
    category: 'handcraft',
    image: 'https://images.unsplash.com/photo-1682668701024-b6508708a764?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Bertoua Crafts',
    rating: 4.8,
    stock: 15,
    isFlashSale: true,
    discount: 18,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'Intricate wood carvings',
    descriptionFr: 'Sculptures en bois complexes'
  },
  {
    id: 23,
    name: 'Peanuts (10kg)',
    nameFr: 'Arachides (10kg)',
    price: 5500,
    region: 'far-north',
    category: 'agriculture',
    image: 'https://images.unsplash.com/photo-1509110646989-7ca4308edb3e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Maroua Farms',
    rating: 4.6,
    stock: 95,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['pickup', 'inter-region'],
    description: 'Fresh roasted peanuts',
    descriptionFr: 'Arachides grillées fraîches'
  },
  {
    id: 24,
    name: 'Bluetooth Speaker',
    nameFr: 'Haut-parleur Bluetooth',
    price: 18500,
    region: 'littoral',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Littoral Fresh Market',
    rating: 4.7,
    stock: 42,
    isFlashSale: true,
    discount: 25,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup'],
    description: 'Portable wireless Bluetooth speaker',
    descriptionFr: 'Haut-parleur Bluetooth sans fil portable'
  },
  {
    id: 25,
    name: 'Used Tablet Samsung',
    nameFr: 'Tablette Samsung Occasion',
    price: 75000,
    region: 'centre',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1679896949191-dc62950076ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Mama Agnes Market',
    rating: 4.2,
    stock: 3,
    isFlashSale: false,
    condition: 'used',
    deliveryOptions: ['pickup'],
    description: 'Samsung tablet in good condition',
    descriptionFr: 'Tablette Samsung en bon état'
  },
  {
    id: 26,
    name: 'Designer Handbag',
    nameFr: 'Sac à Main Design',
    price: 28000,
    region: 'west',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1667366925513-573975457271?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'West Region Textiles',
    rating: 4.5,
    stock: 12,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'inter-region'],
    description: 'Stylish designer handbag',
    descriptionFr: 'Sac à main design élégant'
  },
  {
    id: 27,
    name: 'Coffee Beans (2kg)',
    nameFr: 'Grains de Café (2kg)',
    price: 9500,
    region: 'west',
    category: 'foodstuff',
    image: 'https://images.unsplash.com/photo-1762882807447-3534bff2c831?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'West Region Textiles',
    rating: 4.9,
    stock: 60,
    isFlashSale: false,
    condition: 'new',
    deliveryOptions: ['home-delivery', 'pickup', 'inter-region'],
    description: 'Premium Arabica coffee beans',
    descriptionFr: 'Grains de café Arabica premium'
  },
  {
    id: 28,
    name: 'Men\'s Sneakers',
    nameFr: 'Baskets pour Hommes',
    price: 15000,
    region: 'littoral',
    category: 'fashion',
    image: 'https://images.unsplash.com/photo-1667366925513-573975457271?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400',
    seller: 'Fashion Boutique',
    rating: 3.9,
    stock: 20,
    isFlashSale: false,
    condition: 'used',
    deliveryOptions: ['pickup', 'home-delivery'],
    description: 'Comfortable men\'s sneakers',
    descriptionFr: 'Baskets confortables pour hommes'
  }
];

export const vendors = [
  {
    id: 1,
    name: 'Mama Agnes Market',
    nameFr: 'Marché Mama Agnes',
    region: 'centre',
    rating: 4.8,
    products: 45,
    verified: true,
    badge: 'Top Seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Agnes',
    description: 'Fresh produce and traditional foods',
    descriptionFr: 'Produits frais et aliments traditionnels'
  },
  {
    id: 2,
    name: 'TechHub Douala',
    nameFr: 'TechHub Douala',
    region: 'littoral',
    rating: 4.9,
    products: 120,
    verified: true,
    badge: 'Verified',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TechHub',
    description: 'Latest electronics and gadgets',
    descriptionFr: 'Derniers appareils électroniques et gadgets'
  },
  {
    id: 3,
    name: 'Agro Southwest',
    nameFr: 'Agro Sud-Ouest',
    region: 'southwest',
    rating: 5.0,
    products: 78,
    verified: true,
    badge: 'Premium',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Agro',
    description: 'Organic farming products',
    descriptionFr: 'Produits agricoles biologiques'
  },
  {
    id: 4,
    name: 'Bamenda Fashion House',
    nameFr: 'Maison de Mode Bamenda',
    region: 'northwest',
    rating: 4.7,
    products: 65,
    verified: true,
    badge: 'Top Seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fashion',
    description: 'Traditional and modern fashion',
    descriptionFr: 'Mode traditionnelle et moderne'
  },
  {
    id: 5,
    name: 'Garoua Electronics',
    nameFr: 'Électronique Garoua',
    region: 'north',
    rating: 4.6,
    products: 89,
    verified: true,
    badge: 'Verified',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Garoua',
    description: 'Quality electronics at best prices',
    descriptionFr: 'Électronique de qualité aux meilleurs prix'
  },
  {
    id: 6,
    name: 'Kribi Fresh Seafood',
    nameFr: 'Fruits de Mer Frais Kribi',
    region: 'south',
    rating: 4.9,
    products: 32,
    verified: true,
    badge: 'Premium',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kribi',
    description: 'Fresh catch delivered daily',
    descriptionFr: 'Pêche fraîche livrée quotidiennement'
  },
  {
    id: 7,
    name: 'Bertoua Crafts',
    nameFr: 'Artisanat Bertoua',
    region: 'east',
    rating: 4.5,
    products: 54,
    verified: true,
    badge: 'Verified',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bertoua',
    description: 'Handmade crafts and artifacts',
    descriptionFr: 'Artisanat et artefacts faits main'
  },
  {
    id: 8,
    name: 'Littoral Fresh Market',
    nameFr: 'Marché Frais Littoral',
    region: 'littoral',
    rating: 4.8,
    products: 95,
    verified: true,
    badge: 'Top Seller',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LittoralMarket',
    description: 'Your daily fresh produce source',
    descriptionFr: 'Votre source quotidienne de produits frais'
  },
  {
    id: 9,
    name: 'West Region Textiles',
    nameFr: 'Textiles Région Ouest',
    region: 'west',
    rating: 4.9,
    products: 72,
    verified: true,
    badge: 'Premium',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Textiles',
    description: 'Traditional fabrics and modern designs',
    descriptionFr: 'Tissus traditionnels et designs modernes'
  },
  {
    id: 10,
    name: 'Adamawa Honey',
    nameFr: 'Miel Adamaoua',
    region: 'adamawa',
    rating: 5.0,
    products: 28,
    verified: true,
    badge: 'Premium',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Honey',
    description: 'Pure organic honey from highlands',
    descriptionFr: 'Miel biologique pur des hautes terres'
  }
];

export const flashDeals = products.filter(p => p.isFlashSale);

export const translations = {
  en: {
    home: 'Home',
    categories: 'Categories',
    regions: 'Regions',
    cart: 'Cart',
    account: 'Account',
    search: 'Search products, categories, regions...',
    featured: 'Featured Products',
    flashSales: 'Flash Sales',
    trendingNow: 'Trending Now',
    exploreRegions: 'Explore by Region',
    topVendors: 'Top Vendors',
    popularCategories: 'Popular Categories',
    viewAll: 'View All',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    fcfa: 'FCFA',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    endsIn: 'Ends in',
    off: 'OFF'
  },
  fr: {
    home: 'Accueil',
    categories: 'Catégories',
    regions: 'Régions',
    cart: 'Panier',
    account: 'Compte',
    search: 'Rechercher produits, catégories, régions...',
    featured: 'Produits en Vedette',
    flashSales: 'Ventes Flash',
    trendingNow: 'Tendances',
    exploreRegions: 'Explorer par Région',
    topVendors: 'Meilleurs Vendeurs',
    popularCategories: 'Catégories Populaires',
    viewAll: 'Voir Tout',
    addToCart: 'Ajouter au Panier',
    buyNow: 'Acheter',
    fcfa: 'FCFA',
    inStock: 'En Stock',
    outOfStock: 'Rupture de Stock',
    endsIn: 'Se termine dans',
    off: 'RÉDUCTION'
  }
};

// Delivery pricing based on regions
export const deliveryPricing = {
  sameRegion: 1500,
  interRegion: {
    adjacent: 3000, // Adjacent regions
    far: 5000, // Far regions
  },
  pickup: 0,
};

// Region distance matrix (for delivery cost calculation)
export const regionDistances: Record<string, string[]> = {
  centre: ['littoral', 'east', 'south', 'adamawa'],
  littoral: ['centre', 'west', 'southwest'],
  west: ['littoral', 'northwest', 'southwest'],
  northwest: ['west', 'adamawa'],
  southwest: ['littoral', 'west', 'south'],
  south: ['centre', 'east', 'southwest'],
  east: ['centre', 'south', 'adamawa'],
  adamawa: ['centre', 'north', 'east', 'northwest'],
  north: ['adamawa', 'far-north'],
  'far-north': ['north'],
};

// Mock coupons
export const mockCoupons = [
  {
    code: 'WELCOME10',
    discount: 10,
    type: 'percentage' as 'percentage' | 'fixed',
    minOrder: 20000,
    maxDiscount: 5000,
    valid: true,
  },
  {
    code: 'SAVE5000',
    discount: 5000,
    type: 'fixed' as 'percentage' | 'fixed',
    minOrder: 50000,
    valid: true,
  },
  {
    code: 'FLASH20',
    discount: 20,
    type: 'percentage' as 'percentage' | 'fixed',
    minOrder: 30000,
    maxDiscount: 10000,
    valid: true,
  },
];

// Payment methods
export const paymentMethods = [
  {
    id: 'mtn-momo',
    name: 'MTN Mobile Money',
    nameFr: 'MTN Mobile Money',
    icon: '💛',
    available: true,
  },
  {
    id: 'orange-money',
    name: 'Orange Money',
    nameFr: 'Orange Money',
    icon: '🧡',
    available: true,
  },
  {
    id: 'card',
    name: 'Credit/Debit Card',
    nameFr: 'Carte Bancaire',
    icon: '💳',
    available: true,
  },
  {
    id: 'cash-on-delivery',
    name: 'Cash on Delivery',
    nameFr: 'Paiement à la Livraison',
    icon: '💵',
    available: true,
  },
];
